# Чтение csv/txt файлов

In [5]:
import pandas as pd
import chardet

In [14]:
def get_encoding(filepath: str):
    '''
    Получение кодировки файла
    '''

    # Чтение файла в бинарном формате
    with open(filepath, 'rb') as f:
        data = f.read()

    # Определение кодировки с помощью библиотеки chardet
    encoding_result = chardet.detect(data)

    # Получение информации из результата детекции
    encoding = encoding_result['encoding']

    return encoding

In [18]:
filepath = "data\Dataset_с_параметрами_пропускной_способности_станций.csv" # Путь до файла
encoding = get_encoding(filepath) # Кодировка документа (узнать через Блокнот/через код)
sep = ";" # Разделитель данных (открой файл и посмотри)

data = pd.read_csv(filepath, encoding=encoding, sep=sep)

data.head()

,line_id,line_name,station_id,station_name,entry_id,entry_name,input_doors_count,input_doors_bandwidth,input_doors_total_bandwidth,input_doors_note,...,output_turnstile_note,output_stairs_width,output_stairs_bandwidth,output_stairs_total_bandwidth,output_stairs_note,output_escalator_count,output_escalator_bandwidth,output_escalator_total_bandwidth,note,stop_id
0,12,АРБАТСК-ПОКРОВСК,126,Киевская АПЛ,6,Город,4,3.2,12.8,NaN,...,NaN,0.0,0.0,0.0,NaN,0,0.0,0.0,NaN,9000055
1,12,АРБАТСК-ПОКРОВСК,126,Киевская АПЛ,7,Пригород,7,3.2,22.4,NaN,...,NaN,0.0,0.0,0.0,NaN,0,0.0,0.0,NaN,9000055
2,12,АРБАТСК-ПОКРОВСК,129,Смоленская АПЛ,5,Центр,3,3.2,9.6,NaN,...,NaN,0.0,0.0,0.0,NaN,0,0.0,0.0,NaN,9000056
3,12,АРБАТСК-ПОКРОВСК,131,Арбатская АПЛ,5,Центр,4,3.2,12.8,NaN,...,реверс,0.0,0.0,0.0,NaN,0,0.0,0.0,NaN,9000057
4,12,АРБАТСК-ПОКРОВСК,133,Пл. Революции,3,Запад,4,3.2,12.8,NaN,...,NaN,0.0,0.0,0.0,NaN,0,0.0,0.0,NaN,9000058

In [21]:
filepath = "data\\152022.txt" # Путь до файла
encoding = get_encoding(filepath) # Кодировка документа (узнать через Блокнот/через код)
sep = "," # Разделитель данных (открой файл и посмотри)

data = pd.read_csv(filepath, encoding=encoding, sep=sep)

data.head()

    Time Parameter     Value
0  00:00  RecordID  152022.0
1  00:00       Age      84.0
2  00:00    Gender       0.0
3  00:00    Height      -1.0
4  00:00   ICUType       3.0

# Чтение excel файлов

In [26]:
filepath = "data\Data.xlsx" # Путь до файла
sheet_name = "Sheet_2" # Название листа в excel файле
header = 0 # Индекс строки, которую принять за названия колонок

data = pd.read_excel(filepath, sheet_name=sheet_name, header=header)

data

   id_2 name_2
0     1   John
1     2  Jerry
2     3    Joe
3     4  Julia
4     5  Jessy

In [ ]:
filepath = "data\Data_2.xls" # Путь до файла
sheet_name = "Sheet_2" # Название листа в excel файле
header = 0 # Индекс строки, которую принять за названия колонок

data = pd.read_excel(filepath, sheet_name=sheet_name, header=header)

data

   id_2 name_2
0     1   John
1     2  Jerry
2     3    Joe
3     4  Julia
4     5  Jessy

# Чтение таблиц из html

In [41]:
filepath = "data\page_with_table.html" # Путь до файла
encoding = get_encoding(filepath) # Кодировка документа (узнать через Блокнот/через код)
table_index = 0 # Индекс таблицы, так как в файле может быть несколько таблиц

data = pd.read_html(filepath, encoding=encoding)[table_index]

data

                      Name             Topic    Difficulty
0   Introduction to Python            Python      Beginner
1          Data Structures        Algorithms  Intermediate
2  Machine Learning Basics  Machine Learning      Advanced

# Чтение JSON файлов

In [63]:
filepath = "data\Dates_easy.json" # Путь до файла
encoding = get_encoding(filepath) # Кодировка документа (узнать через Блокнот/через код)

data = pd.read_json(filepath, encoding=encoding, orient="columns")

data

   One  Two
0   60  110
1   60  117
2   60  103
3   45  109
4   45  117
5   60  102

In [64]:
filepath = "data\Dates_difficult.json" # Путь до файла
encoding = get_encoding(filepath) # Кодировка документа (узнать через Блокнот/через код)

data = pd.read_json(filepath, encoding=encoding, orient="columns")
data = data["data"].to_dict()

data = pd.DataFrame(data)

data

   One  Two
0   60  110
1   60  117
2   60  103
3   45  109
4   45  117
5   60  102